// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzvifxqwrozipoyqswva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dmlmeHF3cm96aXBveXFzd3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTY2MzEsImV4cCI6MjA2ODUzMjYzMX0.hI-FENRJRCx8Dld--0k8-BJK8vY35AEshL2i1Zi80ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});